#!/usr/bin/env tsx

import { db } from '@/lib/db';
import { charities, type NewCharity } from '@/lib/schema/charities';

/**
 * Script to manually seed charities into the database
 * Usage: npm run seed-charities
 */

const sampleCharities: NewCharity[] = [
  // International Charities
  {
    name: 'Save the Children',
    slug: 'save-the-children',
    description: 'Save the Children is the world\'s leading independent organization for children in need, with programs in over 120 countries.',
    mission: 'We believe every child deserves a future. In the United States and around the world, we give children a healthy start in life, the opportunity to learn and protection from harm.',
    email: 'contact@savethechildren.org',
    website: 'https://www.savethechildren.org',
    logo: 'https://logo.clearbit.com/savethechildren.org',
    category: 'Children & Youth',
    focusAreas: ['Education', 'Health', 'Child Protection', 'Emergency Response'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Doctors Without Borders',
    slug: 'doctors-without-borders',
    description: 'Doctors Without Borders/Médecins Sans Frontières (MSF) is an international humanitarian medical organization that provides aid in nearly 70 countries.',
    mission: 'We provide medical assistance to people affected by conflict, epidemics, disasters, or exclusion from healthcare.',
    email: 'info@msf.org',
    website: 'https://www.doctorswithoutborders.org',
    logo: 'https://logo.clearbit.com/doctorswithoutborders.org',
    category: 'Health',
    focusAreas: ['Medical Care', 'Emergency Response', 'Epidemics', 'Disaster Relief'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'World Wildlife Fund',
    slug: 'world-wildlife-fund',
    description: 'WWF works to help local communities conserve the natural resources they depend upon, transform markets and policies toward sustainability, and protect and restore species and their habitats.',
    mission: 'To conserve nature and reduce the most pressing threats to the diversity of life on Earth.',
    email: 'contact@wwf.org',
    website: 'https://www.worldwildlife.org',
    logo: 'https://logo.clearbit.com/worldwildlife.org',
    category: 'Environment',
    focusAreas: ['Wildlife Conservation', 'Climate Change', 'Forests', 'Oceans'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'UNICEF',
    slug: 'unicef',
    description: 'UNICEF works in over 190 countries and territories to save children\'s lives, defend their rights, and help them fulfill their potential.',
    mission: 'To advocate for the protection of children\'s rights, to help meet their basic needs and to expand their opportunities to reach their full potential.',
    email: 'contact@unicef.org',
    website: 'https://www.unicef.org',
    logo: 'https://logo.clearbit.com/unicef.org',
    category: 'Children & Youth',
    focusAreas: ['Child Rights', 'Education', 'Health', 'Child Protection', 'Water & Sanitation'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Oxfam International',
    slug: 'oxfam-international',
    description: 'Oxfam is a global movement of people working together to end the injustice of poverty.',
    mission: 'To create lasting solutions to poverty, hunger, and social injustice around the world.',
    email: 'info@oxfam.org',
    website: 'https://www.oxfam.org',
    logo: 'https://logo.clearbit.com/oxfam.org',
    category: 'Hunger & Poverty',
    focusAreas: ['Poverty Relief', 'Gender Justice', 'Climate Action', 'Emergency Response'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'CARE International',
    slug: 'care-international',
    description: 'CARE works around the globe to save lives, defeat poverty, and achieve social justice.',
    mission: 'We seek a world of hope, tolerance and social justice, where poverty has been overcome and people live in dignity and security.',
    email: 'info@care.org',
    website: 'https://www.care.org',
    logo: 'https://logo.clearbit.com/care.org',
    category: 'Hunger & Poverty',
    focusAreas: ['Poverty', 'Gender Equality', 'Emergency Relief', 'Education'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Plan International',
    slug: 'plan-international',
    description: 'Plan International is a development and humanitarian organization that advances children\'s rights and equality for girls.',
    mission: 'We strive for a just world that advances children\'s rights and equality for girls.',
    email: 'info@plan-international.org',
    website: 'https://plan-international.org',
    logo: 'https://logo.clearbit.com/plan-international.org',
    category: 'Children & Youth',
    focusAreas: ['Child Rights', 'Girls\' Education', 'Child Protection', 'Economic Empowerment'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Water.org',
    slug: 'water-org',
    description: 'Water.org is an international nonprofit organization that has positively transformed millions of lives around the world with access to safe water and sanitation.',
    mission: 'We\'re here to bring water and sanitation to the world.',
    email: 'info@water.org',
    website: 'https://water.org',
    logo: 'https://logo.clearbit.com/water.org',
    category: 'Water & Sanitation',
    focusAreas: ['Clean Water', 'Sanitation', 'Microfinance', 'Community Development'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Islamic Relief Worldwide',
    slug: 'islamic-relief-worldwide',
    description: 'Islamic Relief is an international humanitarian organization working to save and transform the lives of some of the world\'s most vulnerable people.',
    mission: 'Inspired by our Islamic faith and guided by our values, we envisage a caring world where communities are empowered, social obligations are fulfilled and people respond as one to the suffering of others.',
    email: 'info@islamic-relief.org',
    website: 'https://www.islamic-relief.org',
    logo: 'https://logo.clearbit.com/islamic-relief.org',
    category: 'Humanitarian Aid',
    focusAreas: ['Emergency Relief', 'Water & Sanitation', 'Education', 'Healthcare'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },

  // Nigerian Charities
  {
    name: 'Nigerian Red Cross Society',
    slug: 'nigerian-red-cross-society',
    description: 'The Nigerian Red Cross Society provides humanitarian services to vulnerable people in Nigeria.',
    mission: 'To prevent and alleviate human suffering, protect life and health and ensure respect for human beings in Nigeria.',
    email: 'info@redcrossnigeria.org',
    website: 'https://www.redcrossnigeria.org',
    logo: 'https://logo.clearbit.com/redcrossnigeria.org',
    category: 'Disaster Relief',
    focusAreas: ['Emergency Response', 'Disaster Relief', 'Health Services', 'Community Support'],
    country: 'Nigeria',
    city: 'Abuja',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Tony Elumelu Foundation',
    slug: 'tony-elumelu-foundation',
    description: 'The Tony Elumelu Foundation empowers African entrepreneurs and catalyzes economic growth across Africa.',
    mission: 'To empower African entrepreneurs to transform the continent through entrepreneurship.',
    email: 'info@tonyelumelufoundation.org',
    website: 'https://www.tonyelumelufoundation.org',
    logo: 'https://logo.clearbit.com/tonyelumelufoundation.org',
    category: 'Economic Empowerment',
    focusAreas: ['Entrepreneurship', 'Youth Empowerment', 'Job Creation', 'Economic Development'],
    country: 'Nigeria',
    city: 'Lagos',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Slum2School Africa',
    slug: 'slum2school-africa',
    description: 'Slum2School Africa is committed to improving the lives of children and young people living in underserved communities across Africa.',
    mission: 'To transform the lives of children in underserved communities through quality education and community development.',
    email: 'info@slum2school.org',
    website: 'https://slum2school.org',
    logo: 'https://logo.clearbit.com/slum2school.org',
    category: 'Education',
    focusAreas: ['Education', 'Community Development', 'Youth Empowerment', 'Poverty Alleviation'],
    country: 'Nigeria',
    city: 'Lagos',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'FATE Foundation',
    slug: 'fate-foundation',
    description: 'FATE Foundation is committed to wealth creation through entrepreneurship development.',
    mission: 'To transform Africa by championing wealth creation through entrepreneurship development.',
    email: 'info@fatefoundation.org',
    website: 'https://www.fatefoundation.org',
    logo: 'https://logo.clearbit.com/fatefoundation.org',
    category: 'Economic Empowerment',
    focusAreas: ['Entrepreneurship', 'Business Development', 'Youth Training', 'Job Creation'],
    country: 'Nigeria',
    city: 'Lagos',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Project Pink Blue',
    slug: 'project-pink-blue',
    description: 'Project Pink Blue provides free cancer screening and treatment for economically disadvantaged women in Nigeria.',
    mission: 'To reduce the incidence and mortality of breast and cervical cancer in Africa through awareness, education, and free screening.',
    email: 'info@projectpinkblue.org',
    website: 'https://www.projectpinkblue.org',
    logo: 'https://logo.clearbit.com/projectpinkblue.org',
    category: 'Health',
    focusAreas: ['Cancer Screening', 'Women\'s Health', 'Healthcare Access', 'Health Education'],
    country: 'Nigeria',
    city: 'Lagos',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Mentally Aware Nigeria Initiative (MANI)',
    slug: 'mentally-aware-nigeria-initiative',
    description: 'MANI is a youth-led non-profit working to reduce the treatment gap for mental illness in Nigeria.',
    mission: 'To promote mental health awareness and provide support for those affected by mental illness in Nigeria.',
    email: 'info@maniafrica.com',
    website: 'https://www.maniafrica.com',
    logo: '/images/MANI.png',
    category: 'Health',
    focusAreas: ['Mental Health', 'Youth Support', 'Health Education', 'Community Awareness'],
    country: 'Nigeria',
    city: 'Lagos',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'She Writes Woman',
    slug: 'she-writes-woman',
    description: 'She Writes Woman is empowering women and girls in underserved communities through education and skills acquisition.',
    mission: 'To empower women and girls to achieve their full potential through education and economic empowerment.',
    email: 'info@shewriteswoman.org',
    website: 'https://www.shewriteswoman.org',
    logo: 'https://logo.clearbit.com/shewriteswoman.org',
    category: 'Women Empowerment',
    focusAreas: ['Women\'s Education', 'Skills Training', 'Gender Equality', 'Community Development'],
    country: 'Nigeria',
    city: 'Lagos',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'The Bloom Foundation',
    slug: 'the-bloom-foundation',
    description: 'The Bloom Foundation supports vulnerable children and families in Nigeria through education and community programs.',
    mission: 'To provide quality education and support for vulnerable children in Nigeria.',
    email: 'info@thebloomfoundation.org',
    website: 'https://www.thebloomfoundation.org',
    logo: 'https://logo.clearbit.com/thebloomfoundation.org',
    category: 'Children & Youth',
    focusAreas: ['Child Education', 'Family Support', 'Community Programs', 'Youth Development'],
    country: 'Nigeria',
    city: 'Abuja',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'African Leadership Academy',
    slug: 'african-leadership-academy',
    description: 'African Leadership Academy identifies, develops and connects young leaders who will transform Africa.',
    mission: 'To develop the next generation of African leaders who will transform the continent.',
    email: 'info@africanleadershipacademy.org',
    website: 'https://www.africanleadershipacademy.org',
    logo: 'https://logo.clearbit.com/africanleadershipacademy.org',
    category: 'Education',
    focusAreas: ['Leadership Training', 'Youth Education', 'Entrepreneurship', 'Pan-African Development'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Education as a Vaccine (EVA)',
    slug: 'education-as-a-vaccine',
    description: 'EVA works to improve access to quality education for children in underserved communities in Nigeria.',
    mission: 'To ensure every Nigerian child has access to quality education.',
    email: 'info@evaafrica.org',
    website: 'https://www.evaafrica.org',
    logo: '/images/EV.png',
    category: 'Education',
    focusAreas: ['Primary Education', 'Educational Access', 'Community Schools', 'Teacher Training'],
    country: 'Nigeria',
    city: 'Abuja',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'FOMWAN Orphanage',
    slug: 'fomwan-orphanage',
    description: 'FOMWAN Orphanage in Ibadan provides care and support for vulnerable children as part of the Federation of Muslim Women\'s Associations in Nigeria.',
    mission: 'To provide quality care, education, and support for orphaned and vulnerable children in Ibadan and surrounding communities.',
    email: 'info@fomwanofficial.org',
    website: 'https://www.fomwanofficial.org',
    logo: 'https://logo.clearbit.com/fomwanofficial.org',
    category: 'Children & Youth',
    focusAreas: ['Child Care', 'Education', 'Community Support', 'Women Empowerment'],
    country: 'Nigeria',
    city: 'Ibadan',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },

  // More Global Charities
  {
    name: 'Feeding America',
    slug: 'feeding-america',
    description: 'Feeding America is the nation\'s largest domestic hunger-relief organization, with a network of 200 food banks.',
    mission: 'To advance change in America by ensuring equitable access to nutritious food for all in partnership with food banks, policymakers, supporters, and the communities we serve.',
    email: 'info@feedingamerica.org',
    website: 'https://www.feedingamerica.org',
    logo: 'https://logo.clearbit.com/feedingamerica.org',
    category: 'Hunger & Poverty',
    focusAreas: ['Food Security', 'Hunger Relief', 'Community Support'],
    country: 'United States',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Habitat for Humanity',
    slug: 'habitat-for-humanity',
    description: 'Habitat for Humanity is a global nonprofit housing organization working in local communities across all 50 states and in approximately 70 countries.',
    mission: 'Seeking to put God\'s love into action, Habitat for Humanity brings people together to build homes, communities and hope.',
    email: 'info@habitat.org',
    website: 'https://www.habitat.org',
    logo: 'https://logo.clearbit.com/habitat.org',
    category: 'Housing & Shelter',
    focusAreas: ['Affordable Housing', 'Community Development', 'Disaster Response'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'American Red Cross',
    slug: 'american-red-cross',
    description: 'The American Red Cross prevents and alleviates human suffering in the face of emergencies by mobilizing the power of volunteers and the generosity of donors.',
    mission: 'The American Red Cross, a humanitarian organization, provides emergency assistance, disaster relief, and disaster preparedness education.',
    email: 'info@redcross.org',
    website: 'https://www.redcross.org',
    logo: 'https://logo.clearbit.com/redcross.org',
    category: 'Disaster Relief',
    focusAreas: ['Emergency Response', 'Blood Services', 'Disaster Relief', 'Health & Safety Training'],
    country: 'United States',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'The Nature Conservancy',
    slug: 'the-nature-conservancy',
    description: 'The Nature Conservancy is a global environmental organization working to create a world where people and nature can thrive.',
    mission: 'To conserve the lands and waters on which all life depends.',
    email: 'info@tnc.org',
    website: 'https://www.nature.org',
    logo: 'https://logo.clearbit.com/nature.org',
    category: 'Environment',
    focusAreas: ['Conservation', 'Climate Change', 'Oceans', 'Forests', 'Fresh Water'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Direct Relief',
    slug: 'direct-relief',
    description: 'Direct Relief improves the health and lives of people affected by poverty or emergencies.',
    mission: 'To improve the health and lives of people affected by poverty or emergency situations by mobilizing and providing essential medical resources.',
    email: 'info@directrelief.org',
    website: 'https://www.directrelief.org',
    logo: 'https://logo.clearbit.com/directrelief.org',
    category: 'Health',
    focusAreas: ['Medical Aid', 'Emergency Response', 'Chronic Disease', 'Maternal Health'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Goodwill Industries',
    slug: 'goodwill-industries',
    description: 'Goodwill Industries International enhances the dignity and quality of life of individuals and families by strengthening communities.',
    mission: 'To enhance the dignity and quality of life of individuals and families by strengthening communities, eliminating barriers to opportunity, and helping people in need reach their full potential through learning and the power of work.',
    email: 'contactus@goodwill.org',
    website: 'https://www.goodwill.org',
    logo: 'https://logo.clearbit.com/goodwill.org',
    category: 'Employment & Training',
    focusAreas: ['Job Training', 'Employment Services', 'Community Development'],
    country: 'United States',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Room to Read',
    slug: 'room-to-read',
    description: 'Room to Read seeks to transform the lives of millions of children in low-income communities by focusing on literacy and gender equality in education.',
    mission: 'To transform the lives of millions of children in low-income communities by partnering to develop literacy skills and a habit of reading among primary school children, and supporting girls to complete secondary school with the skills to negotiate key life decisions.',
    email: 'info@roomtoread.org',
    website: 'https://www.roomtoread.org',
    logo: 'https://logo.clearbit.com/roomtoread.org',
    category: 'Education',
    focusAreas: ['Literacy', 'Girls\' Education', 'Libraries', 'Reading Programs'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Kiva',
    slug: 'kiva',
    description: 'Kiva is an international nonprofit, founded in 2005 and based in San Francisco, with a mission to connect people through lending to alleviate poverty.',
    mission: 'To expand financial access to help underserved communities thrive.',
    email: 'info@kiva.org',
    website: 'https://www.kiva.org',
    logo: 'https://logo.clearbit.com/kiva.org',
    category: 'Economic Empowerment',
    focusAreas: ['Microfinance', 'Entrepreneurship', 'Poverty Alleviation', 'Financial Inclusion'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Charity: Water',
    slug: 'charity-water',
    description: 'charity: water is a nonprofit organization bringing clean and safe drinking water to people in developing countries.',
    mission: 'We\'re a nonprofit organization bringing clean and safe drinking water to people around the world.',
    email: 'info@charitywater.org',
    website: 'https://www.charitywater.org',
    logo: 'https://logo.clearbit.com/charitywater.org',
    category: 'Water & Sanitation',
    focusAreas: ['Clean Water', 'Well Construction', 'Community Development', 'Water Projects'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
  {
    name: 'Heifer International',
    slug: 'heifer-international',
    description: 'Heifer International works with communities around the world to end hunger and poverty while caring for the Earth.',
    mission: 'To end hunger and poverty while caring for the Earth.',
    email: 'info@heifer.org',
    website: 'https://www.heifer.org',
    logo: 'https://logo.clearbit.com/heifer.org',
    category: 'Hunger & Poverty',
    focusAreas: ['Livestock Donation', 'Sustainable Agriculture', 'Income Generation', 'Food Security'],
    country: 'International',
    isActive: true,
    isVerified: true,
    verifiedAt: new Date(),
  },
];

async function seedCharities() {
  try {
    console.log('🌱 Seeding charities...\n');

    for (const charity of sampleCharities) {
      try {
        await db.insert(charities).values(charity).onConflictDoUpdate({
          target: charities.slug,
          set: {
            ...charity,
            updatedAt: new Date(),
          },
        });
        console.log(`✅ Added/Updated: ${charity.name}`);
      } catch (error) {
        console.error(`❌ Error adding ${charity.name}:`, error);
      }
    }

    console.log(`\n✨ Successfully seeded ${sampleCharities.length} charities!`);
  } catch (error) {
    console.error('Error seeding charities:', error);
    process.exit(1);
  }
}

seedCharities();

